// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VAT.api.DataAccess;

namespace VAT.api.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VAT.api.Models.VMT_County", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("baseline_jan_vmt")
                        .HasColumnType("int");

                    b.Property<int>("county_fips")
                        .HasColumnType("int");

                    b.Property<string>("county_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("county_vmt")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date_at_low")
                        .HasColumnType("datetime2");

                    b.Property<float>("mean7_county_vmt")
                        .HasColumnType("real");

                    b.Property<float>("mean7_county_vmt_at_low")
                        .HasColumnType("real");

                    b.Property<float>("mean7_percent_change_from_jan")
                        .HasColumnType("real");

                    b.Property<float>("percent_change_from_jan")
                        .HasColumnType("real");

                    b.Property<float>("percent_change_from_low")
                        .HasColumnType("real");

                    b.Property<string>("state_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("VMT_Countys");
                });
#pragma warning restore 612, 618
        }
    }
}
